package com.cinema.jazz.live;
import java.util.*;

/**
 * All 86+ live channels.
 * Logo priority: local drawable (ch_<id>) → tamashaweb/Wikipedia URL fallback.
 * ChannelAdapter.getLocalLogo() tries "ch_" + id.replace("-","_") first.
 */
public final class ChannelsData {

    public static List<Channel> ALL = Arrays.asList(
        // ── SPORTS ──
        ch("pak-ban",    "PAK v BAN",  "🏏 Sports","sports",
            "https://tamashaweb.com/wp-content/uploads/2024/01/ptv-sports.png",
            "https://cdn02lhr-n.tamashaweb.com:8087/jazzauth/PAKvsBANTS-2026-ABR/playlist.m3u8"),
        ch("ten-sports", "Ten Sports", "🏏 Sports","sports",
            "https://tamashaweb.com/wp-content/uploads/2023/07/ten-sports.png",
            "https://cdn07isb.tamashaweb.com:8087/YlUHeDQb7a/157-3H/playlist.m3u8"),
        ch("ptv-sports", "PTV Sports", "🏏 Sports","sports",
            "https://tamashaweb.com/wp-content/uploads/2024/01/ptv-sports.png",
            "https://cdn21lhr.tamashaweb.com:8087/jazzauth/189H/chunks.m3u8"),
        ch("eurosport",  "Eurosport",  "⚽ Sports","sports",
            "https://tamashaweb.com/wp-content/uploads/2023/07/eurosport.png",
            "https://cdn21lhr.tamashaweb.com:8087/jazzauth/Eurosport-abr/playlist.m3u8"),

        // ── ISLAMIC ──
        ch("saudi-makkah",  "Saudi Makkah",   "🕌 Islamic","religious",
            "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/Saudi_Arabia_TV.svg/200px-Saudi_Arabia_TV.svg.png",
            "https://cdn12isb.tamashaweb.com:8087/YlUHeDQb7a/Saudimakkah(nw)-abr/playlist.m3u8"),
        ch("saudi-madinah", "Saudi Madinah",  "🕌 Islamic","religious",
            "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/Saudi_Arabia_TV.svg/200px-Saudi_Arabia_TV.svg.png",
            "https://cdn12isb.tamashaweb.com:8087/YlUHeDQb7a/SaudiSunnah(NW)-abr/playlist.m3u8"),
        ch("madani-ch",     "Madani Channel", "🕌 Islamic","religious",
            "https://tamashaweb.com/wp-content/uploads/2023/07/madani-channel.png",
            "https://cdn07isb.tamashaweb.com:8087/jazzauth/Madni-abr/playlist.m3u8"),
        ch("paigham-tv",    "Paigham TV",     "🕌 Islamic","religious",
            "https://tamashaweb.com/wp-content/uploads/2023/07/paigham-tv.png",
            "https://cdn22lhr.tamashaweb.com:8087/jazzauth/PaighamTV-abr/playlist.m3u8"),

        // ── NEWS ──
        ch("geo-news",     "Geo News",     "📰 News","news",
            "https://tamashaweb.com/wp-content/uploads/2023/07/geo-news.png",
            "https://cdn07isb.tamashaweb.com:8087/jazzauth/vsat-geonews-abr/playlist_dvr_timeshift-0-3600.m3u8"),
        ch("ary-news",     "ARY News",     "📰 News","news",
            "https://tamashaweb.com/wp-content/uploads/2023/07/ary-news.png",
            "https://cdn07isb.tamashaweb.com:8087/jazzauth/vsat-arynews-abr/playlist.m3u8"),
        ch("hum-news",     "Hum News",     "📰 News","news",
            "https://tamashaweb.com/wp-content/uploads/2023/07/hum-news.png",
            "https://cdn12isb.tamashaweb.com:8087/YlUHeDQb7a/humnews-abr/playlist.m3u8"),
        ch("express-news", "Express News", "📰 News","news",
            "https://tamashaweb.com/wp-content/uploads/2023/07/express-news.png",
            "https://cdn12isb.tamashaweb.com:8087/YlUHeDQb7a/expressnews-abr/playlist.m3u8"),
        ch("samaa-tv",     "Samaa TV",     "📰 News","news",
            "https://tamashaweb.com/wp-content/uploads/2023/07/samaa-tv.png",
            "https://cdn05khi.tamashaweb.com:8087/jazzauth/samaaTV-abr/playlist.m3u8"),
        ch("bol-news",     "BOL News",     "📰 News","news",
            "https://tamashaweb.com/wp-content/uploads/2023/07/bol-news.png",
            "https://cdn12isb.tamashaweb.com:8087/YlUHeDQb7a/BolNews-abr/playlist.m3u8"),
        ch("gnn",          "GNN",          "📰 News","news",
            "https://tamashaweb.com/wp-content/uploads/2023/07/gnn.png",
            "https://cdn12isb.tamashaweb.com:8087/YlUHeDQb7a/GNN-abr/playlist.m3u8"),
        ch("dawn-news",    "Dawn News",    "📰 News","news",
            "https://tamashaweb.com/wp-content/uploads/2023/07/dawn-news.png",
            "https://cdn21lhr.tamashaweb.com:8087/jazzauth/DawnNews-abr/playlist.m3u8"),
        ch("suno-news",    "Suno News",    "📰 News","news",
            "https://tamashaweb.com/wp-content/uploads/2023/07/suno-news.png",
            "https://cdn12isb.tamashaweb.com:8087/YlUHeDQb7a/Suno_News-abr/playlist.m3u8"),
        ch("neo-news",     "Neo News",     "📰 News","news",
            "https://tamashaweb.com/wp-content/uploads/2023/07/neo-news.png",
            "https://cdn24lhr.tamashaweb.com:8087/jazzauth/NeoNews-abr/playlist.m3u8"),
        ch("sun-news",     "Sun News",     "📰 News","news",
            "https://upload.wikimedia.org/wikipedia/en/thumb/6/6d/Sun_News_Pakistan_Logo.png/200px-Sun_News_Pakistan_Logo.png",
            "https://cdn21lhr.tamashaweb.com:8087/jazzauth/SUN-NEWS-abr/playlist.m3u8"),
        ch("ptv-news",     "PTV News",     "📰 News","news",
            "https://tamashaweb.com/wp-content/uploads/2023/07/ptv-news.png",
            "https://cdn05khi.tamashaweb.com:8087/jazzauth/PTVNews-abr/playlist.m3u8"),
        ch("abn-news",     "ABN News",     "📰 News","news",
            "https://upload.wikimedia.org/wikipedia/en/b/b8/Abn_news_logo.jpg",
            "https://cdn22lhr.tamashaweb.com:8087/jazzauth/ABNnews-abr/playlist.m3u8"),
        ch("gtv-news",     "GTV News",     "📰 News","news",
            "https://upload.wikimedia.org/wikipedia/en/a/ad/GTV_News.png",
            "https://cdn12isb.tamashaweb.com:8087/YlUHeDQb7a/GTVNews-abr/playlist.m3u8"),
        ch("aaj-news",     "Aaj News",     "📰 News","news",
            "https://tamashaweb.com/wp-content/uploads/2023/07/aaj-news.png",
            "https://cdn21lhr.tamashaweb.com:8087/jazzauth/AajNews-abr/playlist.m3u8"),
        ch("365-news",     "365 News",     "📰 News","news",
            "https://upload.wikimedia.org/wikipedia/en/8/87/365_News_Logo.jpg",
            "https://cdn22lhr.tamashaweb.com:8087/jazzauth/365News-abr/playlist.m3u8"),
        ch("tamasha-news", "Tamasha News", "📰 News","news",
            "https://tamashaweb.com/wp-content/uploads/2023/07/tamasha.png",
            "https://cdn07isb.tamashaweb.com:8087/jazzauth/Tamasha-News-abr/playlist.m3u8"),
        ch("digital-pak",  "Digital Pak",  "📰 News","news",
            "https://upload.wikimedia.org/wikipedia/en/f/f6/Digital_Pakistan_TV.jpg",
            "https://cdn23lhr.tamashaweb.com:8087/jazzauth/Digital-pak-abr/playlist.m3u8"),
        ch("aljazeera",    "Al Jazeera",   "🌍 News","news",
            "https://tamashaweb.com/wp-content/uploads/2023/07/aljazeera.png",
            "https://cdn05khi.tamashaweb.com:8087/jazzauth/AL-Jazeera-abr/playlist.m3u8"),
        ch("cnn",          "CNN",          "🌍 News","news",
            "https://tamashaweb.com/wp-content/uploads/2023/07/cnn.png",
            "https://cdn22lhr.tamashaweb.com:8087/jazzauth/Livecnn-abr/playlist.m3u8"),
        ch("dw-news",      "DW News",      "🌍 News","news",
            "https://tamashaweb.com/wp-content/uploads/2023/07/dw-news.png",
            "https://cdn12isb.tamashaweb.com:8087/YlUHeDQb7a/DWNews-abr/playlist.m3u8"),
        ch("cgtn-hd",      "CGTN HD",      "🌍 News","news",
            "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/CGTN_logo.svg/200px-CGTN_logo.svg.png",
            "https://cdn21lhr.tamashaweb.com:8087/jazzauth/CgtnHD-abr/playlist.m3u8"),
        ch("24-news",      "24 News",      "📰 News","news",
            "https://tamashaweb.com/wp-content/uploads/2023/07/24-news.png",
            "https://cdn12isb.tamashaweb.com:8087/YlUHeDQb7a/24News-abr/playlist.m3u8"),
        ch("public-tv",    "Public TV",    "📰 News","news",
            "https://upload.wikimedia.org/wikipedia/en/0/09/Public_News_Pakistan.jpg",
            "https://cdn12isb.tamashaweb.com:8087/YlUHeDQb7a/PublicTV-abr/playlist.m3u8"),
        ch("news-one",     "News One",     "📰 News","news",
            "https://upload.wikimedia.org/wikipedia/en/2/24/Newsone_logo.png",
            "https://cdn12isb.tamashaweb.com:8087/YlUHeDQb7a/NewsOne-abr/playlist.m3u8"),
        ch("abb-tak",      "Abb Tak",      "📰 News","news",
            "https://upload.wikimedia.org/wikipedia/en/6/68/Abb_Tak_logo.png",
            "https://cdn12isb.tamashaweb.com:8087/YlUHeDQb7a/abbtak-abr/playlist.m3u8"),
        ch("pnn",          "PNN (Aik News)","📰 News","news",
            "https://upload.wikimedia.org/wikipedia/en/7/71/Aik_News_Logo.jpg",
            "https://cdn12isb.tamashaweb.com:8087/YlUHeDQb7a/PNN-abr/playlist.m3u8"),
        ch("bbc-news",     "BBC News",     "🌍 News","news",
            "https://tamashaweb.com/wp-content/uploads/2023/07/bbc-news.png",
            "https://cdn21lhr.tamashaweb.com:8087/jazzauth/BBCNEWS-abr/playlist.m3u8"),
        ch("trt-world",    "TRT World",    "🌍 News","news",
            "https://tamashaweb.com/wp-content/uploads/2023/07/trt-world.png",
            "https://cdn21lhr.tamashaweb.com:8087/jazzauth/153H/playlist.m3u8"),
        ch("dunya-news",   "Dunya News",   "📰 News","news",
            "https://tamashaweb.com/wp-content/uploads/2023/07/dunya-news.png",
            "https://cdn21lhr.tamashaweb.com:8087/jazzauth/113M/playlist.m3u8"),
        ch("awaz-news",    "Awaz News",    "📰 News","news",
            "https://upload.wikimedia.org/wikipedia/en/b/b2/Awaz_TV_logo.jpg",
            "https://cdn21lhr.tamashaweb.com:8087/jazzauth/120M/playlist.m3u8"),
        ch("capital-tv",   "Capital TV",   "📰 News","news",
            "https://upload.wikimedia.org/wikipedia/en/a/ae/Capital_TV_Pakistan.jpg",
            "https://cdn21lhr.tamashaweb.com:8087/jazzauth/111M/playlist.m3u8"),

        // ── ENTERTAINMENT ──
        ch("ary-digital",  "ARY Digital",       "🎭 Drama","entertainment",
            "https://tamashaweb.com/wp-content/uploads/2023/07/ary-digital.png",
            "https://cdn07lhr.tamashaweb.com:8087/jazzauth/vsat-arydigital-abr/playlist.m3u8"),
        ch("hum-tv",       "Hum TV",            "🎭 Drama","entertainment",
            "https://tamashaweb.com/wp-content/uploads/2023/07/hum-tv.png",
            "https://cdn23lhr.tamashaweb.com:8087/jazzauth/humTV-abr/playlist.m3u8"),
        ch("geo-ent",      "Geo Entertainment", "🎭 Drama","entertainment",
            "https://tamashaweb.com/wp-content/uploads/2023/07/geo-entertainment.png",
            "https://cdn24lhr.tamashaweb.com:8087/jazzauth/GeoEntertainment-abr/playlist.m3u8"),
        ch("green-ent",    "Green Entertainment","🎭 Drama","entertainment",
            "https://tamashaweb.com/wp-content/uploads/2023/07/green-entertainment.png",
            "https://cdn23lhr.tamashaweb.com:8087/jazzauth/Green_Entertainment-abr/playlist.m3u8"),
        ch("ptv-home",     "PTV Home",          "🏠 Entertainment","entertainment",
            "https://tamashaweb.com/wp-content/uploads/2023/07/ptv-home.png",
            "https://cdn23lhr.tamashaweb.com:8087/jazzauth/PTVHome-abr/playlist.m3u8"),
        ch("express-ent",  "Express Entertainment","🎭 Entertainment","entertainment",
            "https://tamashaweb.com/wp-content/uploads/2023/07/express-entertainment.png",
            "https://cdn21lhr.tamashaweb.com:8087/jazzauth/ExpressEntertainment-abr/playlist.m3u8"),
        ch("set-hd",       "SET HD",            "🎭 Entertainment","entertainment",
            "https://tamashaweb.com/wp-content/uploads/2023/07/set-hd.png",
            "https://cdn24lhr.tamashaweb.com:8087/jazzauth/SetEntertainment-abr/playlist.m3u8"),
        ch("bol-ent",      "BOL Entertainment", "🎭 Entertainment","entertainment",
            "https://tamashaweb.com/wp-content/uploads/2023/07/bol-entertainment.png",
            "https://cdn12isb.tamashaweb.com:8087/jazzauth/BolEntertainment-abr/playlist.m3u8"),
        ch("ary-zindagi",  "ARY Zindagi",       "🎭 Drama","entertainment",
            "https://tamashaweb.com/wp-content/uploads/2023/07/ary-zindagi.png",
            "https://cdn21lhr.tamashaweb.com:8087/jazzauth/ARYzindagi-abr/playlist.m3u8"),
        ch("hum-sitaray",  "Hum Sitaray",       "⭐ Entertainment","entertainment",
            "https://tamashaweb.com/wp-content/uploads/2023/07/hum-sitaray.png",
            "https://cdn22lhr.tamashaweb.com:8087/jazzauth/HumSitaray-abr/playlist.m3u8"),
        ch("aan-tv",       "AAN TV",            "🎭 Entertainment","entertainment",
            "https://upload.wikimedia.org/wikipedia/en/2/2b/Aan_TV_Logo.jpg",
            "https://cdn12isb.tamashaweb.com:8087/YlUHeDQb7a/AAN-TV-abr/playlist.m3u8"),
        ch("sab-tv",       "Sab TV",            "🎭 Entertainment","entertainment",
            "https://tamashaweb.com/wp-content/uploads/2023/07/sab-tv.png",
            "https://cdn12isb.tamashaweb.com:8087/YlUHeDQb7a/SabTV-abr/playlist.m3u8"),
        ch("tv-one",       "TV One",            "🎭 Entertainment","entertainment",
            "https://tamashaweb.com/wp-content/uploads/2023/07/tv-one.png",
            "https://cdn12isb.tamashaweb.com:8087/YlUHeDQb7a/TVOne-abr/playlist.m3u8"),
        ch("tv-today",     "TV Today",          "🎭 Entertainment","entertainment",
            "https://upload.wikimedia.org/wikipedia/en/7/77/TV_Today_Pakistan_logo.jpg",
            "https://cdn12isb.tamashaweb.com:8087/jazzauth/TvToday-abr/playlist.m3u8"),
        ch("aurlife",      "AurLife",           "🎭 Entertainment","entertainment",
            "https://upload.wikimedia.org/wikipedia/en/e/ef/AurLife_TV_Logo.jpg",
            "https://cdn21lhr.tamashaweb.com:8087/jazzauth/AurLife-abr/playlist.m3u8"),
        ch("ltn-family",   "LTN Family",        "👨‍👩‍👧 Family","entertainment",
            "https://upload.wikimedia.org/wikipedia/en/0/07/LTN_Family_logo.jpg",
            "https://cdn12isb.tamashaweb.com:8087/YlUHeDQb7a/LTNFamily-abr/playlist.m3u8"),
        ch("aplus",        "A-Plus",            "🎭 Drama","entertainment",
            "https://tamashaweb.com/wp-content/uploads/2023/07/aplus.png",
            "https://cdn12isb.tamashaweb.com:8087/YlUHeDQb7a/Aplus-abr/playlist.m3u8"),
        ch("aaj-ent",      "Aaj Entertainment", "🎭 Entertainment","entertainment",
            "https://tamashaweb.com/wp-content/uploads/2023/07/aaj-entertainment.png",
            "https://cdn12isb.tamashaweb.com:8087/YlUHeDQb7a/AajEntertainment-abr/playlist.m3u8"),
        ch("see-tv",       "See TV",            "👁️ Entertainment","entertainment",
            "https://upload.wikimedia.org/wikipedia/en/1/16/See_TV_logo.jpg",
            "https://cdn12isb.tamashaweb.com:8087/YlUHeDQb7a/seeTV-abr/playlist.m3u8"),
        ch("urooj-tv",     "Urooj TV",          "🎭 Entertainment","entertainment",
            "https://upload.wikimedia.org/wikipedia/en/5/59/Urooj_TV_Logo.jpg",
            "https://cdn07isb.tamashaweb.com:8087/YlUHeDQb7a/117M/playlist.m3u8"),
        ch("atv",          "ATV",               "📺 Entertainment","entertainment",
            "https://upload.wikimedia.org/wikipedia/en/7/72/ATV_Pakistan.jpg",
            "https://cdn07isb.tamashaweb.com:8087/YlUHeDQb7a/123M/chunks.m3u8"),
        ch("bbc-first",    "BBC First",         "🎭 Entertainment","entertainment",
            "https://upload.wikimedia.org/wikipedia/en/6/66/BBC_First_logo.svg",
            "https://cdn21lhr.tamashaweb.com:8087/jazzauth/BBC-First-abr/playlist.m3u8"),
        ch("bbc-brit",     "BBC Brit",          "🎭 Entertainment","entertainment",
            "https://upload.wikimedia.org/wikipedia/en/b/b9/BBC_Brit_logo.svg",
            "https://cdn21lhr.tamashaweb.com:8087/jazzauth/BBC-Brit-abr/playlist.m3u8"),

        // ── KIDS ──
        ch("cartoon-network","Cartoon Network","🧸 Kids","kids",
            "https://tamashaweb.com/wp-content/uploads/2023/07/cartoon-network.png",
            "https://cdn12isb.tamashaweb.com:8087/YlUHeDQb7a/cartoonnetwork-abr/playlist.m3u8"),
        ch("minimax",      "Minimax",        "🚀 Kids","kids",
            "https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Minimax_logo.svg/200px-Minimax_logo.svg.png",
            "https://cdn12isb.tamashaweb.com:8087/YlUHeDQb7a/Minimax-abr/playlist.m3u8"),
        ch("baby-tv",      "Baby TV",        "🍼 Kids","kids",
            "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/BabyTV_logo.svg/200px-BabyTV_logo.svg.png",
            "https://cdn22lhr.tamashaweb.com:8087/jazzauth/BabyTV-abr/playlist.m3u8"),
        ch("bbc-cbeebies", "BBC CBeebies",   "🧸 Kids","kids",
            "https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/CBeebies_2022.svg/200px-CBeebies_2022.svg.png",
            "https://cdn21lhr.tamashaweb.com:8087/jazzauth/BBC-Cbeebies-abr/playlist.m3u8"),

        // ── MOVIES & MUSIC ──
        ch("filmax",       "Filmax",          "🎞️ Movies","movies",
            "https://upload.wikimedia.org/wikipedia/en/4/4e/Filmax_logo.png",
            "https://cdn12isb.tamashaweb.com:8087/YlUHeDQb7a/Filmax-abr/playlist.m3u8"),
        ch("movie-one",    "Movie One",       "🍿 Movies","movies",
            "https://upload.wikimedia.org/wikipedia/en/2/22/Movie_One_Pakistan.jpg",
            "https://cdn21lhr.tamashaweb.com:8087/jazzauth/MovieOne-abr/playlist.m3u8"),
        ch("8xm",          "8xM Music",       "🎵 Music","movies",
            "https://tamashaweb.com/wp-content/uploads/2023/07/ary-musik.png",
            "https://cdn12isb.tamashaweb.com:8087/YlUHeDQb7a/8xm-abr/playlist.m3u8"),
        ch("jalwa-tv",     "Jalwa TV",        "💃 Music","movies",
            "https://upload.wikimedia.org/wikipedia/en/d/d3/Jalwa_TV_logo.jpg",
            "https://cdn12isb.tamashaweb.com:8087/YlUHeDQb7a/jalwa-abr/playlist.m3u8"),
        ch("play-tv",      "Play TV",         "🎶 Music","movies",
            "https://upload.wikimedia.org/wikipedia/en/c/c3/Play_Entertainment_TV.jpg",
            "https://cdn12isb.tamashaweb.com:8087/YlUHeDQb7a/play-abr/playlist.m3u8"),
        ch("srf-movies",   "SRF Movies",      "🎬 Movies","movies",
            "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/SRF_logo.svg/200px-SRF_logo.svg.png",
            "https://cdn21lhr.tamashaweb.com:8087/jazzauth/177H/playlist.m3u8"),
        ch("inplus",       "InPlus Pak",      "⭐ Movies","movies",
            "https://upload.wikimedia.org/wikipedia/en/0/04/InPlus_Pak_logo.jpg",
            "https://cdn23lhr.tamashaweb.com:8087/jazzauth/Inplus-abr/playlist.m3u8"),

        // ── DOCS & LIFESTYLE ──
        ch("discovery-hd", "Discovery HD",         "🦁 Discovery","docs",
            "https://tamashaweb.com/wp-content/uploads/2023/07/discovery.png",
            "https://cdn05khi.tamashaweb.com:8087/jazzauth/DiscoveryHD-abr/playlist.m3u8"),
        ch("cgtn-doc",     "CGTN Documentary",     "🎥 Docs","docs",
            "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/CGTN_logo.svg/200px-CGTN_logo.svg.png",
            "https://cdn23lhr.tamashaweb.com:8087/jazzauth/CgtnDocumentary-abr/playlist.m3u8"),
        ch("animal-planet","Animal Planet",         "🐘 Nature","docs",
            "https://tamashaweb.com/wp-content/uploads/2023/07/animal-planet.png",
            "https://cdn07isb.tamashaweb.com:8087/YlUHeDQb7a/AnimalPlanet-abr/playlist.m3u8"),
        ch("disc-pak",     "Discover Pakistan",     "🇵🇰 Docs","docs",
            "https://upload.wikimedia.org/wikipedia/en/e/e5/PTV_Sports_logo.png",
            "https://cdn12isb.tamashaweb.com:8087/YlUHeDQb7a/DiscoveryPakistan-abr/playlist.m3u8"),
        ch("hum-masala",   "Hum Masala",            "🍳 Food","docs",
            "https://tamashaweb.com/wp-content/uploads/2023/07/hum-masala.png",
            "https://cdn05khi.tamashaweb.com:8087/jazzauth/hummasala-abr/playlist.m3u8"),
        ch("tamasha-women","Tamasha Woman",          "👩 Lifestyle","docs",
            "https://tamashaweb.com/wp-content/uploads/2023/07/tamasha.png",
            "https://cdn21lhr.tamashaweb.com:8087/jazzauth/Tamasha-Women-abr/playlist.m3u8"),
        ch("tamasha-life", "Tamasha Life",           "🌿 Lifestyle","docs",
            "https://tamashaweb.com/wp-content/uploads/2023/07/tamasha.png",
            "https://cdn22lhr.tamashaweb.com:8087/jazzauth/Tamasha-Life-HD-abr/playlist.m3u8"),
        ch("bbc-earth",    "BBC Earth",              "🌍 Nature","docs",
            "https://upload.wikimedia.org/wikipedia/en/4/4c/BBC_Earth_logo.svg",
            "https://cdn22lhr.tamashaweb.com:8087/jazzauth/BBC-Earth-abr/playlist.m3u8"),
        ch("bbc-lifestyle","BBC Lifestyle",          "🌱 Lifestyle","docs",
            "https://upload.wikimedia.org/wikipedia/commons/4/41/BBC_Logo_2021.svg",
            "https://cdn21lhr.tamashaweb.com:8087/jazzauth/BBC-Lifestyle-abr/playlist.m3u8"),
        ch("disc-science", "Discovery Science",      "🔬 Science","docs",
            "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7f/Discovery_Channel_logo_2019.svg/200px-Discovery_Channel_logo_2019.svg.png",
            "https://cdn22lhr.tamashaweb.com:8087/jazzauth/Discovery-Science-abr/playlist.m3u8")
    );

    public static List<Channel> byCategory(String cat) {
        List<Channel> r = new ArrayList<>();
        for (Channel c : ALL) if (cat.equals(c.cat)) r.add(c);
        return r;
    }

    public static List<String> categories() {
        List<String> r = new ArrayList<>();
        Set<String> seen = new LinkedHashSet<>();
        for (Channel c : ALL) if (seen.add(c.cat)) r.add(c.cat);
        return r;
    }

    public static String catLabel(String cat) {
        switch (cat) {
            case "sports":        return "🏏 Sports";
            case "religious":     return "🕌 Islamic / Religious";
            case "news":          return "📰 News";
            case "entertainment": return "🎭 Entertainment & Drama";
            case "kids":          return "🧸 Kids";
            case "movies":        return "🎬 Movies & Music";
            case "docs":          return "🌿 Docs & Lifestyle";
            default:              return cat;
        }
    }

    private static Channel ch(String id, String name, String genre, String cat, String logo, String url) {
        return new Channel(id, name, genre, cat, logo, url);
    }
    private ChannelsData() {}
}
